movieproject/movieapp/urls.py
from django.urls import path

from movieapp import views

app_name = 'movieapp'

urlpatterns = [

    path('', views.index),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.addmov, name='addmov'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    year = models.IntegerField()
    img=models.ImageField()

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from .forms import Movieform
from .models import Movie


def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }

    return render(request, 'index.html', context)


def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)

    # return HttpResponse("this is movie no %s" % movie_id)
    return render(request, "details.html", {'movie': movie})


def addmov(request):
    if request.method == "POST":
        nam = request.POST.get('name', )
        des = request.POST.get('desc', )
        yer = request.POST.get('year', )
        imag = request.FILES['img']
        movie = Movie(name=nam, desc=des, year=yer, img=imag)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = Movieform(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    movie = Movie.objects.get(id=id)
    if request.method == 'POST':
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="desc" placeholder="enter movie description"><br>
    <input type="text" name="year" placeholder="enter movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
    <nav class="navbar navbar-blue bg-dark">
        <a class="navbar-brand" href="#">
          Online movie
        </a>
    </nav>

{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are you sure to delete?<br>
    <input type="submit" value="Delete">
</form>

{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="padding:50px;">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="500" height="225">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h5>{{movie.year}}</h5>
            <h6>{{movie.desc}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method='POST' enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container" style="padding:10px">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4">
            <div class="card" style="background:#F7F5F8;color:black; width: 18rem;height: 15rem;padding:5px";>
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="150">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{desc}}</p>
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            <br>
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-warning" href="{% url 'movieapp:addmov' %}">Add movie</a>
</div>

{% endblock %}